#config
data:
  edf_path: "./data/sub-01_task-motor-imagery_eeg.edf"
  events_path: "./data/task-motor-imagery_events.tsv"
  fs: 500  # frequenza campionamento

preprocessing:
  filter_band: [7, 40]  # mu/beta bands
  filter_order: 4

training:
  window_size: 1000
  stride: 125
  batch_size: 32
  lr: 0.0005
  weight_decay: 0.005
  epochs: 50
  patience: 15
  resume: true
  label_smoothing: 0.1


model:
  name: "EEGNet"  #
#  name: "SimpleEEGNet"
  n_channels: 29   #31
  n_classes: 2

# ── Pipeline spettrogramma
training_spectrogram:
  window_size: 1000   # 2 secondi → più risoluzione tempo-frequenza
  stride: 250
  batch_size: 32
  lr: 0.0005
  weight_decay: 0.005
  epochs: 50
  patience: 10

## ── Pipeline GAF (GAFNet) ──
#training_gaf:
#  window_size: 1000
#  stride: 250
#  batch_size: 32
#  lr: 0.0005
#  weight_decay: 0.005
#  epochs: 50
#  patience: 10
#  gaf_type: "GADF"  #"GASF"
#  image_size: 16
#  dropout: 0.25
#  resume: false


# ── Pipeline ViT ──
training_vit:
  window_size: 1000
  stride: 250
  batch_size: 32
  lr: 0.00005
  weight_decay: 0.005
  dropout: 0.3
  epochs: 50
  patience: 15
  gaf_type: "GASF"  #GASF - #GADF
  image_size: 64
  target_size: 224
  freeze_vit: false
  model_name: "vit_small_patch16_224"   #alternativa --> vit_base_patch16_224 ; deit_tiny_patch16_224 ; vit_small_patch16_224
  resume: false

split:
  train: [0, 113000]
  val: [113000, 137000]
  test: [137000, 160000]
